### ISSUE TITLE
implicit dependency on `JetBrains\PhpStorm` namespace

### ISSUE THREAD

**Issue by jsawo** [blumilksoftware/codestyle#14]
`Config` class references `Jetbrains/PhpStorm` namespace which is not available outside of PhpStorm.
The code runs correctly even if they're not available since these are just attributes but IDE (other than PhpStorm) will complain if it parses this class.

**Comment by krzysztofrewak** [comment]
@jsawo, just FYI, I opened small PR in Jetbrains repository: https://github.com/JetBrains/phpstorm-attributes/pull/10

If the pull request would be accepted, I'll add [JetBrains/phpstorm-attributes](https://github.com/JetBrains/phpstorm-attributes) to `require-dev` section of `composer.json`.
