### ISSUE TITLE
Compatibility with PHP 7.4

### ISSUE THREAD

**Issue by mtracz** [blumilksoftware/codestyle#18]
We should allow use this package with projects with PHP version lower than 8.0. I would like to support PHP version from 7.4.

The package should be full functionality in the projects with PHP 7.4 and above.

**Comment by krzysztofrewak** [comment]
I'm closing this issue. PHP 7.4 lost its support on November 2021 (6 months ago!) and will lose security fixes in 5 months. We should not support old versions.
