### ISSUE TITLE
Enforce trailing commas

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/codestyle#30]
I would like to change all of these:
```php
    public function __construct(
        protected Client $client
    ) {
    }
```

into this:
```php
    public function __construct(
        protected Client $client,
    ) {
    }
```

The same for standard multiline method arguments and of course multiline arrays.

**Comment by krzysztofrewak** [comment]
@Baakoma, do you think it's possible to enable this in match-case too?

**Comment by Baakoma** [comment]
I'm not sure if the current version of `TrailingCommaInMultilineFixer` works with it. There are only 3 possible elements atm:
- arrays
- arguments
- parameters
