### ISSUE TITLE
SwitchCaseSemicolonToColonFixer incompatible with PHP 8.1

### ISSUE THREAD

**Issue by Baakoma** [blumilksoftware/codestyle#42]
The `SwitchCaseSemicolonToColonFixer` doesn't work properly with a new PHP 8.1 feature - enums.

![image](https://user-images.githubusercontent.com/16743001/143840117-593802f1-2995-45a8-9577-51c7cac5b171.png)

**Comment by krzysztofrewak** [comment]
Did you try to update ECS beneath?

**Comment by Baakoma** [comment]
ECS 9.4.70 doesn't have updated fixer. Branch 10.X (beta) would probably work.

**Comment by Baakoma** [comment]
https://github.com/symplify/easy-coding-standard/releases/tag/10.0.0
