### ISSUE TITLE
Space after & in methods params (PHP 8.1)

### ISSUE THREAD

**Issue by mtracz** [blumilksoftware/codestyle#45]
On PHP 8.1, `PhpCsFixer\Fixer\FunctionNotation\FunctionTypehintSpaceFixer` add space after `&` sign in methods params.

```php
// Before fix
private function test(array &$param): void
// After fix:
private function test(array & $param): void
```

Expected formatting:
```php
private function test(array &$param): void
```

**Comment by krzysztofrewak** [comment]
It should be fixed with next release of PHP CS Fixer or ECS.

https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6100
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5776
