### ISSUE TITLE
Checking of images

### ISSUE THREAD

**Issue by kamilpiech97** [blumilksoftware/codestyle#53]
Code style checks images and shouldn't because it throws errors like below, I think.
![obraz](https://user-images.githubusercontent.com/29115024/161235702-f5db511d-8c1f-4234-b4a3-897eb3a933ff.png)

For repeat that bug, image file is needed for example in public directory of Laravel app.

**Comment by krzysztofrewak** [comment]
@kamilpiech97, the problem may lay here: https://github.com/blumilksoftware/codestyle/blob/main/src/Config.php#L63
