### ISSUE TITLE
Problem with enums which have simple syntax

### ISSUE THREAD

**Issue by MrHDOLEK** [blumilksoftware/codestyle#83]
Each time we run the linter, the linter breaks it down even more.The problem only occurs with enums
Before lint:
```
enum Operator: string
{
    case equal = "{$eq}";
}

or 

enum Operator: string
{
    case equal = "$eq";
}

After lint:

enum Operator: string
{
        case equal = "{

    public $eq}";
}

or

enum Operator: string
{
    case equal = "

    public $eq";
}

And next lint:

enum Operator: string
{
    case equal = "{

    public 

    public $eq}";
}

**Comment by krzysztofrewak** [comment]
Why do you even have variables in your enum cases? It's forbidden, because enum case value must be a contant.

![obraz](https://user-images.githubusercontent.com/10898728/193753203-845778d5-a45e-4031-902d-26bcfe762f07.png)

**Comment by MrHDOLEK** [comment]
@krzysztofrewak This is a test case that I came across by the way

**Comment by krzysztofrewak** [comment]
You cannot fix style of invalid PHP code. Of course you can try to raise this topic in the original PHP CS Fixer repository, but I think it's a wrong example of using this tool.

Btw. original PHP CS Fixer fails here too, as checked here https://www.phptools.online/php-checker/result/2cb95dbe-c453-43ee-b5c3-55a63d94a328:
```php
<?php

enum Operator: string {
    case Equal = "$eq";
}
```

transformed into:
```php
<?php

enum Operator: string
{
    case Equal = "public $eq";
}
```
