### ISSUE TITLE
Empty line before return

### ISSUE THREAD

**Issue by kamilpiech97** [blumilksoftware/codestyle#94]
I would like to have empty line before return in functions.

Before:
```
public function foo(){
$bar = 100;
return $bar;
}
```

After:
```
public function foo(){
$bar = 100;

return $bar;
}
```

**Comment by krzysztofrewak** [comment]
Ref: https://mlocati.github.io/php-cs-fixer-configurator/#version:3.16|fixer:blank_line_before_statement
